name: Node.js CI and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: 'npm'

    - name: Update lockfileVersion
      run: npm install --package-lock

    - name: Upgrade node-pre-gyp
      run: npm install --save @mapbox/node-pre-gyp

    - name: Install dependencies
      run: |
        npm install
        npm install seedrandom

    - name: Set Git credentials
      run: |
        git config --global credential.username "${{ secrets.GIT_USER_NAME }}"

    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
        git config --global user.name "${{ secrets.GIT_USER_NAME }}"

    - name: Set the NODE_AUTH_TOKEN
      run: |
        export NODE_AUTH_TOKEN="${{ secrets.GH_TOKEN }}"

    - name: Build and deploy project
      if: github.ref == 'refs/heads/main'
      run: |
        npm run build
        gh-pages -d build
